# Generated by Django 4.0.4 on 2022-05-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('commandText', models.TextField()),
                ('Bandwidth', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.TextField(max_length=17, unique=True)),
                ('username', models.TextField(default=None)),
                ('password', models.TextField(default=None)),
                ('keyPair', models.TextField(default=None)),
            ],
        ),
    ]
