# Generated by Django 4.0.4 on 2022-05-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DdosTool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='keyPairs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('fileName', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='commands',
            name='Bandwidth',
        ),
        migrations.AddField(
            model_name='commands',
            name='bandwidth',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='devices',
            name='ip',
            field=models.TextField(max_length=15, unique=True),
        ),
    ]
